Function input feature for time-dependent boundary conditions
SimVascular/svZeroDSolver pull request #108
Opened 2024-05-14 02:15 UTC by kharold23

## Current situation
Closes #89 

## Release Notes 
- Added a new parameter `fn` to flow and pressure boundary conditions that takes in a string
- Interprets the string as a function of time, represented by the variable `t`
- The value of the boundary condition is calculated at each time step by evaluating the function at `t` = the current time value.

## Documentation
Time-dependent boundary conditions can now be input using a function passed in as a string. The function is of the variable `t`, or time. For example:
`"bc_values": {
                "fn": "2.0 * (4*atan(1.)) * COS(2.0 * (4*atan(1.)) * t)"
}`

## Testing
Test case `test_time_dependent_block` added to `test_io.py`, which runs json files `timeDep_Flow.json` and `timeDep_Pressure.json`.

## Code of Conduct & Contributing Guidelines 
- [x] I agree to follow the [Code of Conduct](https://github.com/SimVascular/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/SimVascular/.github/blob/main/CONTRIBUTING.md).

2024-05-29 03:48 UTC, ktbolt commented
I ran the `pulsatileFlow_CStenosis_steadyPressure`  case on Ubuntu 22 and got the following exception
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Maximum number of non-linear iterations reached.
```
You need to add catching exceptions in the Python testing code.

2024-05-30 00:42 UTC, ktbolt commented on src/model/Parameter.cpp
> +    parser.compile(expression_string, expression);
It is very easy for a user to add an incorrect math expression so you need to have a try/catch here and also throw an exception if `parser.compile()` returns false.

2024-05-30 00:53 UTC, ktbolt commented
We don't want to mix external software with our source code so the `exprtk.hpp` file should not be in `svZeroDSolver/src/`. We need to add a `ThirdParty` directory and put the `exprtk.hpp` file in a sub-directory of it.

2024-05-30 00:57 UTC, ktbolt commented
Also I see that there is Docker container file in `svZeroDSolver/container/profiling` for Ubuntu 22, you can use this to test I think.

2024-06-24 19:23 UTC, menon-karthik requested changes
Almost ready! Just some minor comments.

2024-06-24 19:23 UTC, menon-karthik commented on src/model/FlowReferenceBC.cpp
> +  // std::cout << system << std::endl;
Remove this line.

2024-06-24 19:23 UTC, menon-karthik commented on tests/cases/timeDep_Flow.json
> +                "fn": "2.0 * (4*atan(1.)) * COS(2.0 * (4*atan(1.)) * t)"
Have all math functions in either upper or lower case?

2024-06-24 19:23 UTC, menon-karthik commented on tests/cases/timeDep_Pressure.json
> +                "fn": "2.0 * (4*atan(1.)) * COS(2.0 * (4*atan(1.)) * t)"
Have all math functions in either upper or lower case?

2024-06-24 19:23 UTC, menon-karthik commented on src/model/Parameter.cpp
> +    // Docs say that thi assignment will result in undefined behaviour,
Typo in the comment.

2024-06-24 19:23 UTC, menon-karthik commented on tests/test_io.py
> +        assert np.isclose(flow[i], calc_val, rtol=0.01)
Is 0.01 the smallest tolerance that we can get with exprtk?

2025-02-06 22:32 UTC, mrp089 commented
@menon-karthik can this be merged?

2025-03-20 17:42 UTC, mrp089 commented
@menon-karthik, @ncdorn, do you know if this can be merged? I think @szafronjm would be interested in using that

2025-03-20 18:02 UTC, menon-karthik commented
@mrp089 This is currently stalled because we could not figure out why one of the tests is failing. But it can be used by directly pulling the feature branch for now: https://github.com/kharold23/svZeroDSolver/tree/time-dependent

2025-03-20 23:20 UTC, ArashPartow commented
@menon-karthik  would mind rebasing/synching this branch to the tip and giving it another go - as the test results seem to have disappeared.

2025-06-11 18:16 UTC, ncdorn commented
we should rebase this branch and figure out if it can be merged @kharold23 @menon-karthik

2025-07-30 18:41 UTC, ncdorn commented
I will close this as I have taken over this PR on my own fork and have opened the draft pull request #186 to handle these changes.

2025-07-30 18:41 UTC, closed without merging