Update documentation with new features and instructions for new blocks
SimVascular/svZeroDSolver pull request #113
Opened 2024-06-27 00:02 UTC by menon-karthik

## Current situation
Closes #66 
We recently had a few new features implemented (or in soon-to-be-merged PRs). So I made some updates to the documentation to reflect those changes. 

## Release Notes 
* Added a new page documenting how to add new blocks.
* Added a new section on contributing to the code.
* Added documentation on #108 
* Added documentation on #109 
* Added short summary of available blocks (including new ones)

## Documentation
This is the documentation.

## Testing
Documentation build. Did not change anything else.

## Code of Conduct & Contributing Guidelines 
- I agree to follow the [Code of Conduct](https://github.com/SimVascular/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/SimVascular/.github/blob/main/CONTRIBUTING.md).

2024-07-08 21:35 UTC, mrp089 requested changes
Looks very nice! Thank you for updating the documentation! I added a few minor ideas.

2024-07-08 21:35 UTC, mrp089 commented on docs/pages/main.md
> +Prescribed (transient) flow           | MODEL::FlowReferenceBC      | `FLOW`                | `Q`: Time-dependent flow values \n `t`: Time steps \n `fn`: Mathematical expression
Indicate that it's either (`Q` and `t`) or `fn`

2024-07-08 21:35 UTC, mrp089 commented on docs/pages/main.md
> +Note that the `FLOW` and `PRESSURE` boundary conditions accept mathematical expressions in `bc_values`. For an example where values of the boundary condition are specified as a function of time, see
Might be easier to read if the examples were included here (and easier to see for new users that mathematical expressions are possible).

2024-07-08 21:35 UTC, mrp089 commented on docs/pages/developer_guide.md
> +  * The tests are automatically run when pushing changes to the developer's remote branch on Github.
Good thing to write this down

2024-07-08 21:35 UTC, mrp089 commented on docs/pages/add_block.md
> +    GenericBlock(int id, Model *model)
Maybe something like `MyNewBlock` instead of `GenericBlock`

2024-07-08 21:35 UTC, mrp089 commented on docs/pages/add_block.md
> +  * The names `Param_1`, ... , `Param_N` should be the same as the parameter names within the block definition in the `.json` configuration/input file.
should or have to?

2024-07-08 21:35 UTC, mrp089 commented on docs/pages/add_block.md
> +* The class should have a `setup_dofs(DOFHandler &dofhandler)` function.
should or has to?

2024-07-08 21:35 UTC, mrp089 commented on docs/pages/add_block.md
> +e*dP_out/dt + f*Q_out*Q_out + g*P_out + h*I_1 = 0
Write in math mode?

2024-07-08 21:35 UTC, mrp089 commented on docs/pages/add_block.md
> +  * *Note: Not all blocks will require the `update_time` and `update_solution` functions.*
Would change the language above from "should" to something like "must"

2024-07-08 21:35 UTC, mrp089 commented on docs/pages/add_block.md
> +* Add `GenericBlock.h` and `GenericBlock.cpp` to `src/model/CMakeLists.txt`
Would consistently move something like `MyNewBlock`

2024-07-09 12:48 UTC, mrp089 commented
The `macos-11` GitHub runner is [not available anymore](https://github.com/actions/runner-images/issues/9255) as of July, so I removed it.

I added a `macos-latest` runner (and `ubuntu-latest`) so we always stay up to date. However, there seems to be a problem with `conda`. Up to you, @menon-karthik, if you want to do this upgrade now or leave it for a later PR.

2024-07-09 23:39 UTC, menon-karthik commented
> The `macos-11` GitHub runner is [not available anymore](https://github.com/actions/runner-images/issues/9255) as of July, so I removed it.
> 
> I added a `macos-latest` runner (and `ubuntu-latest`) so we always stay up to date. However, there seems to be a problem with `conda`. Up to you, @menon-karthik, if you want to do this upgrade now or leave it for a later PR.

I think it's a good idea to stay ahead of the curve, so let's upgrade that right away. I fixed the `conda` problem by using [conda-incubator](https://github.com/conda-incubator/setup-miniconda) to find `conda` and add it to the path. Also, it looks like `macos-12` is also going to be removed soon. I will create a new issue and PR to upgrade that just so it is recorded.

2024-07-10 10:59 UTC, mrp089 approved these changes

2024-07-10 11:00 UTC, merged