svZeroDGUI Tool
SimVascular/svZeroDSolver pull request #122
Opened 2024-08-19 22:53 UTC by emilinmathew

Adding svZeroDGUI Tool

## Current situation
Addresses #121. Allows users to create 0D model input files through an intuitive graphical user interface.

## Release Notes 
- Java-based Web App: Utilizes Flask for backend, Node.js for server-side logic, and Cypress for testing.
- Node Management: Users can add nodes interactively within the graph representation.
- Edge Drawing: Intuitive UI for drawing edges or connections between nodes.
- Integrated Validation: Built-in validation framework to check consistency for svZeroDSolver.

## Documentation
Linked in docs/pages/GUI.md

## Testing
Passes all existing tests & added more unit tests written through Cypress for E2E testing web platforms. 

## Code of Conduct & Contributing Guidelines 
- [Yes] I agree to follow the [Code of Conduct](https://github.com/SimVascular/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/SimVascular/.github/blob/main/CONTRIBUTING.md).

2024-08-26 18:17 UTC, menon-karthik requested changes
Looks good! Mostly comments about documentation.

2024-08-26 18:17 UTC, menon-karthik commented on .github/workflows/img2text.yml
> +name: e2e-tests
Change to GUI-tests

2024-08-26 18:17 UTC, menon-karthik commented on .github/workflows/img2text.yml
> +    runs-on: ubuntu-latest
Run this on macos too? I can't remember if the other PR was also being tested only on Ubuntu, but if it is, maybe try to change that to ubuntu and macos?

2024-08-26 18:17 UTC, menon-karthik commented on .github/workflows/img2text.yml
> +      - name: Print Current Directory
Is this required?

2024-08-26 18:17 UTC, menon-karthik commented on .github/workflows/test.yml
> +            ./svZeroD_interface_test02 ../../../../Release ../../test_02/svzerod_tuned.json
Make indentation consistent

2024-08-26 18:17 UTC, menon-karthik commented on applications/create_0dmodel/app.py
I would change the directory to `applications/svZeroDGUI` (to match the name of the application mentioned in the documentation). Same for dirgraph

2024-08-26 18:17 UTC, menon-karthik commented on applications/create_0dmodel/static/css/style.css
(1) Add a comment at the top saying what this file is for; (2) add comments above each section with a sentence saying what that section is. 
Most user/developers (including me) are not familiar with CSS

2024-08-26 18:17 UTC, menon-karthik commented on applications/create_0dmodel/static/css/vessel_icon.png
Are there two vessel images? I remember seeing the one in vessel.png during our discussions. What is this second one for?

2024-08-26 18:17 UTC, menon-karthik commented on cypress/downloads/graph_data.json
Is this an output of the cypress testing or is it the reference json used to compare with in the test? If it is an output of the tests, does it need to be stored in the repository?

2024-08-26 18:17 UTC, menon-karthik commented on docs/pages/GUI.md
> +1. Navigate to the `applications folder` and then to the `create_0dmodel` subdirectory.
Navigate to the `applications` folder (typo in the position of `)

2024-08-26 18:17 UTC, menon-karthik commented on docs/pages/GUI.md
> +2. Launch the `app.py` file.
Provide a code block for steps 1-2?

2024-08-26 18:17 UTC, menon-karthik commented on applications/create_0dmodel/static/js/app.js
Add more documentation/comments to this file?

2024-08-26 18:17 UTC, menon-karthik commented on applications/create_0dmodel/static/js/cytoscape-edgehandles.js
Same as above: Add more documentation/comments to this file?

2024-08-26 21:34 UTC, emilinmathew commented on applications/create_0dmodel/static/css/vessel_icon.png
Deleted the second one! Was the first iteration image

2024-08-26 21:37 UTC, emilinmathew commented on cypress/downloads/graph_data.json
Deleted this folder - thanks for catching it! We don't need it. I used it for storing the downloaded files during development.

2024-08-27 19:00 UTC, menon-karthik requested changes
Almost there!

2024-08-27 19:00 UTC, menon-karthik commented on applications/svZeroDGUI/static/js/app.js
> +                            color = '#FF00FF';
Would be good to retain the comment saying what color the code corresponds to (for all the colors below)

2024-09-04 17:37 UTC, menon-karthik approved these changes

2024-09-04 17:37 UTC, merged