Fix OpenLoopCoroanry equations
SimVascular/svZeroDSolver pull request #125
Opened 2024-08-22 20:11 UTC by menon-karthik

## Current situation
Closes #107 

The equations for the open loop coronary block were missing a few terms relating to the initial condition. While fixing this, I also noticed that the equation for the steady state initial condition was wrong. 

## Release Notes 
* Added new functions `Block::setup_initial_state_dependent_params` and `Model::setup_initial_state_dependent_parameters` to set up block-specific parameters that depend on the initial state vector
* Added new terms to the OpenLoopCoronary equations to account for the initial condition.
* Fixed the steady state equations for OpenLoopCoronaryBC
* Miscellaneous: Minor edits to the WindkesselBC documentation
* Miscellaneous: Allow a user to run the solver without specifying the name of the output. Default output file will be written with name `output.csv`. This is already a feature when running using the Python API. Just added it to the CMake build executable. 

## Documentation
 
* Updated docs to add new equations for OpenLoopCoronaryBC

## Testing
Tests passing. 

## Code of Conduct & Contributing Guidelines 
- [x] I agree to follow the [Code of Conduct](https://github.com/SimVascular/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/SimVascular/.github/blob/main/CONTRIBUTING.md).

2024-09-19 17:57 UTC, JonathanPham requested changes
See comments.

2024-09-19 17:57 UTC, JonathanPham commented on src/model/OpenLoopCoronaryBC.h
> + * m}\left(R_{v}+R_{a m}\right) \left(P_{c i m}(0)-P_{i m}(0)+P_{i
Should the "\left(P_{c i m}(0)-P_{i m}(0)" term in line 71 be "\left(-P_{c i m}(0)+P_{i m}(0)" (basically, switched signs)? Does that agree with your math, @menon-karthik?

2024-09-19 17:57 UTC, JonathanPham commented on src/model/OpenLoopCoronaryBC.h
> + * m}\left(R_{v} + R_{a m}\right)\left(P_{cim}(0)-P_{i m}(0)+P_{i m}\right)+R_{a
Should the "\left(P_{cim}(0)-P_{i m}(0)" term in line 93 be "\left(-P_{cim}(0)+P_{i m}(0)" (basically, switched signs)?

2024-09-19 17:57 UTC, JonathanPham commented on src/model/OpenLoopCoronaryBC.h
> + * &C_{i m} R_{v} Q_{in}-V_{i m}+C_{i m} \left(-P_{c i m}(0)+P_{i m}(0)-P_{i
Should the "\left(-P_{c i m}(0)+P_{i m}(0)" term in line 63 be "\left(P_{c i m}(0)-P_{i m}(0)" instead? Basically, switched signs?

2024-09-19 17:57 UTC, JonathanPham commented on src/model/OpenLoopCoronaryBC.h
> + * \mathbf{c}^{e}=\left[\begin{array}{c}C_{i m}\left(-P_{i m}+P_{i m}(0)-P_{c i
Should the "+P_{i m}(0)-P_{c i" term in line 91 be "-P_{i m}(0)+P_{c i" instead (basically, switched signs)?

2024-09-19 17:57 UTC, JonathanPham commented on src/model/OpenLoopCoronaryBC.cpp
> +        Cim * (-Pim + Pv + this->Pim_0 - this->P_Cim_0);
Should "this->Pim_0 - this->P_Cim_0" in line 80 be "-this->Pim_0 + this->P_Cim_0" (basically, switched signs)? Because I think all the "Vim" terms in the original equation should be replaced with "Vim - Cim * (P_Cim_0 - Pim_0)". Does that agree with your math, @menon-karthik?

2024-09-19 17:57 UTC, JonathanPham commented on src/model/OpenLoopCoronaryBC.cpp
> +        Cim * (Rv + Ram) * (Pim + this->P_Cim_0 - this->Pim_0);
Should "this->P_Cim_0 - this->Pim_0" in line 83 be "-this->P_Cim_0 + this->Pim_0" (basically, switched signs)?

2024-09-19 19:04 UTC, menon-karthik commented
@JonathanPham responding to all the above comments simultaneously below:

I think the current math is correct. @AndreaZanoni and I verified the expression and also compared the numerical solution with an analytical solution (which it matches with). We plan to add the analytical solution to the tests in a following PR (see #99).

The main fix was to replace `Pim` with `Pim + this->P_Cim_0 - this->Pim_0`

2024-09-23 23:08 UTC, JonathanPham approved these changes
Okay, sounds good.

2024-09-23 23:08 UTC, merged