Added option to specify cardiac period
SimVascular/svZeroDSolver pull request #127
Opened 2024-08-27 19:38 UTC by rjrios915

Addresses #126 

Added option to specify cardiac period under simulation parameters

## Current situation
*Link any open issues or PRs related to this PR. Please ensure that all non-trivial PRs are first tracked and discussed in an existing GitHub issue or discussion.*

## Release Notes 
*Add a bullet point list summary of the feature and possible migration guides if this is a breaking change so this section can be added to the release notes.*

## Documentation
 
*Please ensure that you properly document any additions.*

## Testing
*Please ensure that the PR meets the testing requirements set by GitHub Actions.*
 
*In addition, please ensure all modified and new code is covered by tests.*

## Code of Conduct & Contributing Guidelines 
- [ ] I agree to follow the [Code of Conduct](https://github.com/SimVascular/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/SimVascular/.github/blob/main/CONTRIBUTING.md).

2024-08-28 18:32 UTC, menon-karthik commented
@rjrios915 @JonathanPham Please make sure the tests are passing! 

Also, just wondering if it might be better to specify the cardiac cycle period within the relevant block that is driving the cardiac cycle (like the cardiac chamber)? For example, the currently implemented `ClosedLoopHeartPulmonary` block has this implemented within the block. It might make more sense to do this because the cycle period is not a parameter of the entire simulation really, it is only a parameter of the block that is driving the heart beat.

2024-09-27 19:04 UTC, menon-karthik commented
@rjrios915 @JonathanPham Not sure why the tests are still failing but can you rebase this branch with the master so it it using the most recent version please?

2024-10-01 18:33 UTC, rjrios915 commented
Hello! All test cases except the data visualization should now be passing. As for where the cardiac period is defined, I think it could be useful to do so globally. The solver already utilizes a global period to calculate step size, number of cycles, and the time per cycle when outputting a single cardiac cycle even when there is no heart block, so I was thinking adding it to simulation parameters would make it easy for users to change the value if needed.

2024-10-07 22:05 UTC, menon-karthik requested changes, later dismissed
@rjrios915 We should make sure your changes are consistent with what the code is currently doing. I have commented on specific changes and added links to where they might be inconsistent with the current code. Here's a quick summary:

Currently, `model->cardiac_cycle_period` is initialized as -1.0 here:
https://github.com/SimVascular/svZeroDSolver/blob/edd6156c07f12cf0a1fadf973768343dbba478c8/src/model/Model.h#L94

`model->cardiac_cycle_period` remains -1.0 until it is specified by a block, at which point we make sure that the newly specified value matches the value read previously from any other block (if any). I have provided examples of how that is checked in my comments below.  

If no value has been specified after all blocks have been read, a default value of 1.0 is set. This is in `Model::finalize` and I have also provided a link to that code block in my comments below.

Please make sure your current changes are consistent with that. Mainly, the default should be 1.0 and you should check that any newly specified value is consistent with previously specified values (if any).

2024-10-07 22:05 UTC, menon-karthik commented on src/solve/Solver.cpp
> +  if (simparams.sim_cardiac_period > 0) {
Since we are now specifying cardiac cycle period in multiple places, add a condition to check that they are all consistent. See two examples below.

For time-varying parameters:
https://github.com/SimVascular/svZeroDSolver/blob/edd6156c07f12cf0a1fadf973768343dbba478c8/src/model/Model.cpp#L169-L175

For closed-loop heart block:
https://github.com/SimVascular/svZeroDSolver/blob/edd6156c07f12cf0a1fadf973768343dbba478c8/src/solve/SimulationParameters.cpp#L510-L517

2024-10-07 22:05 UTC, menon-karthik commented on src/solve/SimulationParameters.cpp
> +  sim_params.sim_cardiac_period = sim_config.value("cardiac_period", 0.0);
Should the default value be 1.0? That is consistent with the code below:
https://github.com/SimVascular/svZeroDSolver/blob/edd6156c07f12cf0a1fadf973768343dbba478c8/src/model/Model.cpp#L205-L207

2024-10-07 22:05 UTC, menon-karthik commented on src/solve/SimulationParameters.h
> +  double sim_cardiac_period{0.0};  ///< Cardiac period
Same comment as above about the default value.

2024-10-22 20:08 UTC, rjrios915 commented
Hello! We ran into the issue where the initialization of cardiac period to 1 within the model and simulation parameters separately cause an error when one would automatically be 1 but the other some valid non 1 value. To resolve this, both the model and parameters initialize the cardiac period to -1 unless specified else where. If both values are -1, then solver.h sets the value to 1 (like what was happening in Model::Finalize). If both values are larger than 0, there is a check to make sure the values are consistent. If one is -1 and the other is greater than 0, then that value is set as the cardiac cycle. 

The other idea we had was to pass the parameters to the model constructor so this process could happen like originally when the model is initialized, but I was unsure of how to go about this.

Let me know your thoughts! All the tests should be passing.

2024-10-30 22:04 UTC, ncdorn commented
@rjrios915 ensure that documentation for cardiac period has been added

2025-02-06 22:34 UTC, mrp089 commented
What else needs to be done to merge this (if we still want to merge it)?

2025-03-05 00:03 UTC, ncdorn commented
We do still want to merge this. I will meet with @rjrios915 this week to finalize. Ricky - are all the tests passing and do we still need to address karthik's earlier comments?

2025-03-05 12:47 UTC, mrp089 commented
Sounds good! You might need another (empty) commit to run the tests again because GitHub automatically deletes the logs when they're too old.

2025-03-11 01:59 UTC, rjrios915 commented
I addressed the previous issues by adding checks to make sure that there are no conflicting periods. I also added tests to check that the code is properly throwing errors.

2025-03-11 17:53 UTC, ncdorn commented
@mrp089 @menon-karthik The calibrator and solver tests for this PR are failing due to a GLIBCXX not found error, is this a dependency issue in the testing environment? Any idea why this might be happening?

2025-03-11 17:55 UTC, menon-karthik commented
> @mrp089 @menon-karthik The calibrator and solver tests for this PR are failing due to a GLIBCXX not found error, is this a dependency issue in the testing environment? Any idea why this might be happening?

Trying to figure this out right now. Having the same issue with some commits for the JOSS paper.

2025-03-11 19:25 UTC, menon-karthik commented
Update: I have a fix for this. But also want to fix #147 while I'm at it.

2025-03-12 21:38 UTC, ncdorn commented
Still failing the ubuntu-latest test. Do we need to do something to ensure the tests are running with the updated workflows?

2025-03-13 12:09 UTC, menon-karthik commented
> Still failing the ubuntu-latest test. Do we need to do something to ensure the tests are running with the updated workflows?

You have to rebase with the latest commits in master so they are included in your branch.

2025-03-14 03:04 UTC, mrp089 commented
You can format your code automatically, e.g., in VS Code: https://code.visualstudio.com/docs/cpp/cpp-ide

2025-03-19 23:02 UTC, ncdorn commented
all tests are passing here - @menon-karthik are we good to merge this? There was a new test case added to make sure we are catching mismatched cardiac period errors, maybe you want to look over that quickly.

2025-03-27 03:12 UTC, ncdorn approved these changes

2025-03-27 03:12 UTC, ncdorn commented
still need 1 more review on this to merge it I think

2025-06-10 17:58 UTC, ncdorn commented
@rjrios915 It appears that this branch got mixed up with the branch in #168

2025-06-24 18:45 UTC, ncdorn requested changes

2025-06-24 18:45 UTC, ncdorn commented on src/model/OpenLoopCoronaryBC.h
typo in microvascular

2025-06-24 18:46 UTC, ncdorn approved these changes
Looks good to me

2025-06-24 18:47 UTC, ncdorn commented
@mrp089 do you want to review this before we merge?

2025-06-26 15:00 UTC, ncdorn commented
@mrp089 do you care if we merge this before or after #176

2025-07-31 02:08 UTC, mrp089 requested changes, later dismissed
Minor: exclude your changes in the `.github` folder from this PR.

Apart from that, it looks good to me. It would be good to document the new option. Unfortunately, I have no idea where to put that after the documentation was moved away from this repository. I'll let @ktbolt sort that out.

2025-07-31 02:39 UTC, ktbolt commented
@mrp089 The important thing is that users can now find the documentation ! 

I think most SimVascular developers have updated the web documentation, very easy to do in fact.

2025-09-23 18:50 UTC, ncdorn approved these changes

2025-09-23 18:51 UTC, merged