Fixed doxygen warnings and make the build fail for undocumented code
SimVascular/svZeroDSolver pull request #72
Opened 2023-11-09 00:00 UTC by menon-karthik

Closes #46 

I fixed the previous warnings by adding the necessary documentation. The github actions should now fail and prevent undocumented code from being merged.

2023-11-09 00:11 UTC, menon-karthik commented
The documentation is failing to build because the github actions can't find a package that it could find a few hours ago! I checked that it isn't from my changes by pushing a "test" commit [in this branch](https://github.com/StanfordCBCL/svZeroDPlus/compare/master...menon-karthik:svZeroDPlus:test_docs) where the only change from`StanfordCBCL:master` is that I removed one random word in the documentation in `Block.h`. So although that branch is essentially the same as `StanfordCBCL:master`, the documentation fails to build with the same error. @mrp089 @ktbolt have you seen this before?

2023-11-09 00:25 UTC, ktbolt commented
@menon-karthik I've not seen this before, just tried to rerun it and it failed.

2023-11-09 00:39 UTC, menon-karthik commented
@mrp089 did some digging and it turns out the package that is failing was updated today. Fingers crossed that this resolves itself.

2023-11-09 19:58 UTC, mrp089 commented
@menon-karthik, if you push to this branch now, does the documentation build?

2023-11-09 20:13 UTC, menon-karthik commented
> @menon-karthik, if you push to this branch now, does the documentation build?

Nope.

2023-11-09 20:16 UTC, mrp089 commented
Try downgrading `mattnotmitt/doxygen-action`: https://github.com/mattnotmitt/doxygen-action

Maybe this only affects the `edge` version.

2023-11-10 20:13 UTC, mrp089 commented
@menon-karthik, happy to merge this first and then I'll deal with the conflicts in #74

2023-11-14 17:28 UTC, mrp089 requested changes
Looks great! Thanks for doing this! Just some minor things

2023-11-14 17:28 UTC, mrp089 commented on src/interface/interface.cpp
> +  // interface->output_interval_ = simparams.output_interval;
Not used? Remove?

2023-11-14 18:51 UTC, mrp089 approved these changes

2023-11-14 18:52 UTC, merged