Rename svZeroDPlus to svZeroDSolver
SimVascular/svZeroDSolver pull request #91
Opened 2023-12-16 01:23 UTC by menon-karthik

## Current situation
Addresses #86 and #35. The move from StanfordCBCL to SimVascular involved renaming the repo to svZeroDSolver for consistency. The name therefore had to be updated in several places within the repo. 

## Release Notes 
- Main change is the name being updated in the docs, cmake files, github actions, etc.
- Another important change is the renaming of the python interface. It used to be called `svzerodplus`. Since the name `svzerodsolver` is already taken by the main executable, I thought it would be a good idea to rename the python interface `pysvzerod`. Please let me know what you think @richterjakob!

## Documentation
 
This PR mostly updates the docs. No code changes. 

## Testing
Github actions are passing.

## Code of Conduct & Contributing Guidelines 
- I agree to follow the [Code of Conduct](https://github.com/SimVascular/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/SimVascular/.github/blob/main/CONTRIBUTING.md).

2023-12-16 01:26 UTC, menon-karthik commented
@richterjakob I requested your review because I might have broken some things in the python interface and docker container while renaming things. Please don't feel like you need to spend too much time on this, but just wanted to make sure those two things are working. I'm assuming the automatic testing doesn't check if the docker container is working.

2023-12-16 17:53 UTC, mrp089 requested changes
Thanks for making it happen, @menon-karthik! Let's have a release party in the new year!

Good from my side, just two more places to change paths. Maybe run one final `grep -ir stanfordcbcl` on the repository.

2023-12-16 17:53 UTC, mrp089 commented on docs/pages/main.md
> +For implementation details, have a look at the [source code](https://github.com/StanfordCBCL/svZeroDSolver).
StanfordCBCL -> SimVascular

2023-12-16 17:53 UTC, mrp089 commented on docs/pages/main.md
> +pip install git+https://github.com/StanfordCBCL/svZeroDSolver.git
StanfordCBCL -> SimVascular

2023-12-21 13:53 UTC, mrp089 approved these changes

2023-12-22 03:18 UTC, menon-karthik commented
@mrp089 Thanks for approving! I'll wait for @richterjakob to look at it whenever he gets a chance before merging (no hurry).

2024-01-04 12:15 UTC, mrp089 commented
Merging, as @richterjakob and I want to use the new name in https://github.com/StanfordCBCL/svSuperEstimator. He accepts the name changes with a tear in his eye.

2024-01-04 12:15 UTC, merged